import type { ReactNode } from "react";
import { createContext, useContext } from "react";
import { useLocalStorage } from "~/hooks/useLocalStorage";

export const LANGUAGES = ["English", "한국어", "中文"] as const;
export type LanguageType = (typeof LANGUAGES)[number];

export const UI_TEXT = {
	header: {
		title: {
			English: "Welcome to Bible AI",
			한국어: "바이블 AI에 오신 것을 환영합니다",
			中文: "欢迎来到 Bible AI",
		},
		description: {
			English:
				"Read the Bible with deeper understanding. Get helpful background insights and thoughtful reflection questions for every passage.",
			한국어:
				"성경을 더 깊이 이해하고 묵상할 수 있도록 돕는 도우미입니다. 각 본문마다 이해를 돕는 배경 설명과 생각해 볼 질문을 제공합니다.",
			中文: "帮助您更深入地理解和默想圣经。为每段经文提供背景说明与引导思考的问题，让阅读更加扎实而有意义。",
		},
	},
	navigation: {
		prev: {
			English: "Prev",
			한국어: "이전 장",
			中文: "上一章",
		},
		next: {
			English: "Next",
			한국어: "다음 장",
			中文: "下一章",
		},
	},
	aiTools: {
		tabs: {
			devotion: {
				English: "Devotional Reflection",
				한국어: "말씀 묵상",
				中文: "灵修反思",
			},
			freeForm: {
				English: "Ask Questions",
				한국어: "질문하기",
				中文: "提问",
			},
		},
		disclaimer: {
			English:
				"This content is generated by AI and may not fully reflect theological nuance. Please consult Scripture and trusted sources for careful study.",
			한국어:
				"이 콘텐츠는 AI가 생성한 것으로, 성경과 신뢰할 수 있는 자료를 함께 참고하시기 바랍니다.",
			中文: "本内容由 AI 生成，请结合圣经及可信资料加以查证。",
		},
		loading: {
			English: "Thinking...",
			한국어: "생각 중...",
			中文: "思考中...",
		},
		error: {
			English: "Failed to fetch AI response. Please try again.",
			한국어: "AI 응답을 가져오지 못했습니다. 다시 시도해주세요.",
			中文: "获取 AI 响应失败，请重试。",
		},
		refresh: {
			button: {
				English: "Refresh",
				한국어: "새로고침",
				中文: "刷新",
			},
			rateLimit: {
				English: "Too many refresh requests. Please try again in a few minutes.",
				한국어: "새로고침 요청이 너무 많습니다. 잠시 후 다시 시도해주세요.",
				中文: "刷新请求过多，请几分钟后再试。",
			},
		},
		chat: {
			aiName: "Cutie",
			welcome: {
				English: "Hi! I'm Cutie. Ask me anything about this chapter!",
				한국어: "안녕하세요! 저는 Cutie예요. 이 장에 대해 무엇이든 질문해 주세요!",
				中文: "你好！我是 Cutie。有关本章的任何问题都可以问我！",
			},
			placeholder: {
				English: "Ask a question about this chapter...",
				한국어: "이 장에 대해 질문해 보세요...",
				中文: "提问关于本章的问题...",
			},
			send: {
				English: "Send",
				한국어: "보내기",
				中文: "发送",
			},
		},
	},
} as const;

interface LanguageContextValue {
	language: LanguageType;
	setLanguage: (lang: LanguageType) => void;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(
	undefined,
);

export function LanguageProvider({ children }: { children: ReactNode }) {
	const [language, setLanguage] = useLocalStorage<LanguageType>(
		"bible-ai:language",
		"한국어",
	);

	return (
		<LanguageContext.Provider value={{ language, setLanguage }}>
			{children}
		</LanguageContext.Provider>
	);
}

export function useLanguageContext() {
	const context = useContext(LanguageContext);
	if (!context) {
		throw new Error(
			"useLanguageContext must be used within a LanguageProvider",
		);
	}
	return context;
}
